#!/bin/bash

set -x

python setup.py bdist_egg
echo "from wikicast import __main__; __main__.cli()" > runner.py

ARROW_PRE_0_15_IPC_FORMAT=1 \
SPARK_HOME=$(python -c "import pyspark; print(pyspark.__path__[0])") \
spark-submit \
    --master 'local[*]' \
    --driver-memory 24g \
    --conf spark.sql.shuffle.partitions=24 \
    --packages \
        graphframes:graphframes:0.7.0-spark2.4-s_2.11 \
    --py-files "dist/*.egg" \
    runner.py "$@"
