#!/bin/bash

set -x

SPARK_HOME=$(python -c "import pyspark; print(pyspark.__path__[0])") \
PYSPARK_DRIVER_PYTHON=jupyter \
PYSPARK_DRIVER_PYTHON_OPTS=notebook \
pyspark \
    --master 'local[*]' \
    --conf spark.driver.memory=8g \
    --conf spark.sql.shuffle.partitions=8 \
    --packages \
        graphframes:graphframes:0.7.0-spark2.4-s_2.11
